service:
  appName: ngo-demo
  clusterName: ngo-demo-local
sentinel:
  flowRules:
    resource: "abc"
    tokenCalculateStrategy: 0 #flow.Direct
    controlBehavior: 0 #flow.Reject
    threshold: 1
    statIntervalInMs: 5000
