service:
  appName: newsclient-omad-go
  clusterName: newsclient-omad-go-docker-cm_test
httpServer:
  port: 12001
  mode: debug
log:
  - name: default
    path: ./log
    level: info
    format: txt
    errorPath: ./error
pprof:
  switch: true
  port: 12002
